'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, ChevronDown, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, X } from 'lucide-react'

type Product = { id: string; name: string; price: number; image: string; description: string; category: string }
type CartItem = Product & { quantity: number; variant?: string }

const variants = [
  ['Blue Floral', '/images/tumblers/tumbler-blue-floral.png'],
  ['White Floral', '/images/tumblers/tumbler-white-floral.png'],
  ['Purple Floral', '/images/tumblers/tumbler-purple-floral.png'],
  ['Pink Floral', '/images/tumblers/tumbler-pink-floral.png'],
] as const

const products: Product[] = [
  { id: 'bloom', name: 'Bloom Tumbler', price: 749, image: variants[0][1], description: '1200 ml stainless steel tumbler with a reusable straw.', category: 'Drinkware' },
  { id: 'cloud', name: 'Cloud Headphones', price: 799, image: '/images/headphones/headphones-pink.jpg', description: 'Wireless Bluetooth sound with soft, comfortable cushions.', category: 'Audio' },
  { id: 'desk', name: 'Bloom Keyboard + Mouse', price: 849, image: '/images/bloom 1.jpeg', description: 'A soft pastel desk set for a calmer workspace.', category: 'Gaming / Desk' },
  { id: 'mouse', name: 'Glow Mouse', price: 459, image: '/images/glow 2.jpeg', description: 'A compact wireless mouse with a little more personality.', category: 'Accessories' },
]
const formatPrice = (value: number) => `₹${value.toLocaleString('en-IN')}`

export default function NavAirStorefront() {
  const [variant, setVariant] = useState(0)
  const [slide, setSlide] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)
  const [cartOpen, setCartOpen] = useState(false)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [cart, setCart] = useState<CartItem[]>([])
  const [faq, setFaq] = useState<number | null>(0)

  const promos = [
    { label: 'Bloom Tumbler', kicker: 'A brighter way to hydrate', image: variants[variant][1], price: 749, tone: 'mint' },
    { label: 'Cloud Headphones', kicker: 'Soft sound for loud days', image: products[1].image, price: 799, tone: 'sky' },
    { label: 'Keyboard + Mouse', kicker: 'Refresh your desk setup', image: products[2].image, price: 849, tone: 'peach' },
    { label: 'Glow Mouse', kicker: 'Small move, big mood', image: products[3].image, price: 459, tone: 'lilac' },
  ]

  useEffect(() => { const timer = setInterval(() => setSlide((value) => (value + 1) % promos.length), 5000); return () => clearInterval(timer) }, [promos.length])
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart])
  const shipping = cart.length ? 99 : 0
  const total = subtotal + shipping
  const count = cart.reduce((sum, item) => sum + item.quantity, 0)

  function add(product: Product, selectedVariant?: string) { setCart((items) => { const key = `${product.id}-${selectedVariant || ''}`; const existing = items.find((item) => `${item.id}-${item.variant || ''}` === key); return existing ? items.map((item) => item === existing ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1, variant: selectedVariant }] }); setCartOpen(true) }
  function change(item: CartItem, amount: number) { setCart((items) => items.flatMap((current) => current === item ? (current.quantity + amount > 0 ? [{ ...current, quantity: current.quantity + amount }] : []) : [current])) }

  return <div className="storefront" id="top">
    <div className="announcement"><Sparkles size={14} /> Bloom Tumbler · 1200 ml · ₹749 <a href="#shop">Shop now <ArrowRight size={14} /></a></div>
    <header className="store-header"><a className="logo" href="#top">NAV<span />AIR</a><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#shop" onClick={() => setMenuOpen(false)}>Shop</a><a href="#categories" onClick={() => setMenuOpen(false)}>Categories</a><a href="#bloom" onClick={() => setMenuOpen(false)}>Tumblers</a><a href="#cloud" onClick={() => setMenuOpen(false)}>Audio</a><a href="#about" onClick={() => setMenuOpen(false)}>About</a></nav><div className="header-tools"><button aria-label="Search"><Search size={19} /></button><button onClick={() => setCartOpen(true)} aria-label={`Cart with ${count} items`}><ShoppingBag size={19} />{count > 0 && <b>{count}</b>}</button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div></header>

    <main>
      <section className="hero section-wrap"><div className="hero-copy"><p className="eyebrow">Modern products for everyday life</p><h1>Make everyday<br /><em>feel lighter.</em></h1><p>Thoughtfully selected essentials for your desk, commute, and daily rituals.</p><div className="hero-actions"><a className="primary-button" href="#shop">Shop the collection <ArrowRight size={16} /></a><a className="under-link" href="#about">Why NAV AIR</a></div></div><div className="hero-visual"><div className="hero-orbit" /><span className="hero-tag">NEW<br /><strong>DROP</strong></span><img src={variants[variant][1]} alt={`${variants[variant][0]} Bloom Tumbler`} /><div className="hero-label"><span>01 / 04</span><strong>{variants[variant][0]}</strong><small>Bloom Tumbler · {formatPrice(749)}</small></div><div className="swatches">{variants.map(([name], index) => <button key={name} className={variant === index ? 'selected' : ''} onClick={() => setVariant(index)} aria-label={`Select ${name}`}><i className={`swatch s${index}`} /></button>)}</div></div></section>

      <section className="promo-carousel section-wrap" aria-label="Promotions"><div className={`promo-card ${promos[slide].tone}`}><div><p className="eyebrow">NAV AIR edit · 0{slide + 1}</p><h2>{promos[slide].label}</h2><p>{promos[slide].kicker}</p><strong>{formatPrice(promos[slide].price)}</strong><a className="primary-button" href="#shop">Shop now <ArrowRight size={16} /></a></div><img src={promos[slide].image} alt={promos[slide].label} /></div><div className="carousel-controls">{promos.map((promo, index) => <button key={promo.label} onClick={() => setSlide(index)} className={slide === index ? 'active' : ''} aria-label={`Show ${promo.label}`} />)}</div></section>

      <section className="shop section-wrap" id="shop"><div className="section-intro"><div><p className="eyebrow">The collection</p><h2>Good things,<br /><em>ready to go.</em></h2></div><p>Compact, useful, and designed to bring a little lift to the everyday.</p></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><div className="product-image"><span>{product.category}</span><img src={product.image} alt={product.name} /><button onClick={() => add(product, product.id === 'bloom' ? variants[variant][0] : undefined)} aria-label={`Add ${product.name} to cart`}><Plus size={18} /></button></div><div className="product-info"><div><h3>NAV AIR {product.name}</h3><p>{product.description}</p></div><strong>{formatPrice(product.price)}</strong></div><button className="add-link" onClick={() => add(product, product.id === 'bloom' ? variants[variant][0] : undefined)}>Add to cart <ArrowRight size={15} /></button></article>)}</div></section>

      <section className="feature bloom-feature section-wrap" id="bloom"><div><p className="eyebrow">01 · Drinkware</p><h2>Hydration,<br /><em>with personality.</em></h2><p>Bloom is a 1200 ml stainless steel tumbler made for hot and cold drinks, busy commutes, slow mornings, and everything between.</p><a className="light-button" href="#shop">Shop Bloom <ArrowRight size={15} /></a></div><img src={variants[variant][1]} alt="NAV AIR Bloom floral tumbler" /><div className="feature-points"><span><b>1200</b>ML CAPACITY</span><span><b>HOT + COLD</b>READY</span><span><b>4</b>FLORAL COLORS</span></div></section>
      <section className="variant-row section-wrap"><div className="section-intro centered"><div><p className="eyebrow">Find your flower</p><h2>Pick your<br /><em>colour story.</em></h2></div><p>Blue, white, purple, or pink. Your everyday, your way.</p></div><div className="variant-grid">{variants.map(([name, image], index) => <button className={`variant ${variant === index ? 'chosen' : ''}`} key={name} onClick={() => setVariant(index)}><img src={image} alt={name} /><strong>{name}</strong><small>{formatPrice(749)}</small></button>)}</div></section>
      <section className="feature cloud-feature section-wrap" id="cloud"><div className="cloud-image"><img src={products[1].image} alt="NAV AIR Cloud Headphones" /></div><div><p className="eyebrow">02 · Audio</p><h2>Your own<br /><em>little cloud.</em></h2><p>Wireless Bluetooth sound, deep bass, soft ear cushions, and a lightweight foldable build for wherever the day takes you.</p><div className="chips"><span>Wireless</span><span>Deep bass</span><span>Foldable</span></div><button className="primary-button" onClick={() => add(products[1])}>Add to cart · {formatPrice(799)}</button></div></section>
      <section className="categories section-wrap" id="categories"><div className="section-intro centered"><div><p className="eyebrow">Shop by category</p><h2>Find your<br /><em>next favourite.</em></h2></div></div><div className="category-grid"><a href="#shop"><span>Drinkware</span><small>Bloom Tumbler</small><ArrowRight size={18} /></a><a href="#cloud"><span>Audio</span><small>Cloud Headphones</small><ArrowRight size={18} /></a><a href="#shop"><span>Gaming / Desk</span><small>Keyboard + Mouse</small><ArrowRight size={18} /></a><a href="#shop"><span>Accessories</span><small>Glow Mouse</small><ArrowRight size={18} /></a></div></section>
      <section className="about section-wrap" id="about"><div className="about-badge">na<span>✦</span></div><div><p className="eyebrow">Why NAV AIR</p><h2>Useful can be<br /><em>beautiful too.</em></h2><p>We look for modern, practical products that earn their place in your day. No noise, no clutter — just things that feel good to use.</p></div><ul><li>Thoughtfully selected products</li><li>Modern everyday design</li><li>Shopping made simple</li></ul></section>
      <section className="faq section-wrap"><div><p className="eyebrow">Good to know</p><h2>Questions,<br /><em>answered.</em></h2></div><div>{['How much is shipping?', 'What is Bloom made for?', 'Can I choose a different Bloom colour?'].map((question, index) => <div className="faq-item" key={question}><button onClick={() => setFaq(faq === index ? null : index)}><span>{question}</span><ChevronDown size={18} /></button>{faq === index && <p>{index === 0 ? 'Standard shipping is ₹99 per order across India.' : index === 1 ? 'Bloom is made for hot and cold drinks and holds 1200 ml.' : 'Yes. Select your preferred colour before adding Bloom to your cart.'}</p>}</div>)}</div></section>
    </main>
    <footer><div className="footer-main"><a className="logo" href="#top">NAV<span />AIR</a><p>Everyday essentials,<br /><em>with a little lift.</em></p><a className="primary-button" href="#shop">Shop everything <ArrowRight size={15} /></a></div><div className="footer-bottom"><span>© 2026 NAV AIR</span><span>Support · Policies · Contact</span><span>Made for the everyday</span></div></footer>

    {cartOpen && <div className="overlay" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">Your cart</p><h2>{count ? `${count} ${count === 1 ? 'item' : 'items'}` : 'Your cart is empty'}</h2></div><button onClick={() => setCartOpen(false)} aria-label="Close cart"><X size={20} /></button></div>{cart.length ? <><div className="drawer-items">{cart.map((item) => <div className="drawer-item" key={`${item.id}-${item.variant}`}><img src={item.image} alt="" /><div><strong>{item.name}</strong>{item.variant && <small>{item.variant}</small>}<span>{formatPrice(item.price)}</span><div className="quantity"><button onClick={() => change(item, -1)} aria-label="Decrease quantity"><Minus size={13} /></button><b>{item.quantity}</b><button onClick={() => change(item, 1)} aria-label="Increase quantity"><Plus size={13} /></button></div></div></div>)}</div><div className="summary"><p><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></p><p><span>Shipping</span><strong>{formatPrice(shipping)}</strong></p><p className="total"><span>Total</span><strong>{formatPrice(total)}</strong></p><button className="primary-button full" onClick={() => { setCartOpen(false); setCheckoutOpen(true) }}>Checkout <ArrowRight size={15} /></button></div></> : <div className="empty"><ShoppingBag size={30} /><p>Good things are waiting.</p><button className="primary-button" onClick={() => setCartOpen(false)}>Keep shopping</button></div>}</aside></div>}
    {checkoutOpen && <Checkout cart={cart} subtotal={subtotal} shipping={shipping} total={total} onClose={() => setCheckoutOpen(false)} />}
  </div>
}

function Checkout({ cart, subtotal, shipping, total, onClose }: { cart: CartItem[]; subtotal: number; shipping: number; total: number; onClose: () => void }) { const [form, setForm] = useState({ fullName: '', email: '', phone: '', address: '', landmark: '', city: '', state: '', pincode: '' }); const [status, setStatus] = useState(''); const update = (key: string, value: string) => setForm({ ...form, [key]: value }); async function submit(event: React.FormEvent) { event.preventDefault(); setStatus('Submitting…'); try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || process.env.REACT_APP_BACKEND_URL || 'http://localhost:5000'}/api/orders/create`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, mobile: form.phone, product: cart.map((item) => `${item.name}${item.variant ? ` (${item.variant})` : ''} x${item.quantity}`).join(', '), color: cart.find((item) => item.variant)?.variant || '', price: total }) }); if (!response.ok) throw new Error('Order failed'); setStatus('Order received. We will be in touch shortly.'); } catch { setStatus('We could not submit the order right now. Please try again.'); } } return <div className="overlay"><div className="checkout"><button className="close-checkout" onClick={onClose} aria-label="Close checkout"><X size={20} /></button><div className="checkout-summary"><p className="eyebrow">NAV AIR checkout</p><h2>Almost<br /><em>yours.</em></h2>{cart.map((item) => <div className="checkout-item" key={`${item.id}-${item.variant}`}><img src={item.image} alt="" /><span>{item.name}{item.variant && ` · ${item.variant}`}<small>Qty {item.quantity}</small></span><strong>{formatPrice(item.price * item.quantity)}</strong></div>)}<p className="line"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></p><p className="line"><span>Shipping</span><strong>{formatPrice(shipping)}</strong></p><p className="line grand"><span>Total</span><strong>{formatPrice(total)}</strong></p></div><form onSubmit={submit}><p className="eyebrow">Delivery details</p><div className="form-grid">{[['fullName','Full name'],['email','Email'],['phone','Phone'],['address','Address'],['landmark','Landmark (optional)'],['city','City'],['state','State'],['pincode','PIN code']].map(([key, label]) => <label key={key} className={key === 'address' || key === 'landmark' ? 'wide' : ''}>{label}<input required={key !== 'landmark'} value={form[key as keyof typeof form]} onChange={(event) => update(key, event.target.value)} /></label>)}</div><button className="primary-button full" type="submit">Place order <ArrowRight size={15} /></button>{status && <p className="form-status">{status}</p>}<small className="secure-note">Standard shipping · ₹99 · No payment is collected here.</small></form></div></div> }

export { products, variants }
