import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CaretDown as ChevronDown, List as Menu, Minus, Plus, MagnifyingGlass as Search, ShoppingBag, Sparkle, X } from '@phosphor-icons/react';
import { toast } from 'sonner';

const variants = [
  ['Blue Floral', '/images/tumblers/tumbler-blue-floral.png'], ['White Floral', '/images/tumblers/tumbler-white-floral.png'], ['Purple Floral', '/images/tumblers/tumbler-purple-floral.png'], ['Pink Floral', '/images/tumblers/tumbler-pink-floral.png'],
];
const products = [
  { id: 'bloom', name: 'Bloom Tumbler', price: 749, image: variants[0][1], description: '1200 ml stainless steel tumbler with a reusable straw.', category: 'Drinkware' },
  { id: 'cloud', name: 'Cloud Headphones', price: 799, image: '/images/headphones/headphones-pink.jpg', description: 'Wireless Bluetooth sound with soft, comfortable cushions.', category: 'Audio' },
  { id: 'desk', name: 'Bloom Keyboard + Mouse', price: 849, image: '/images/bloom 1.jpeg', description: 'A soft pastel desk set for a calmer workspace.', category: 'Gaming / Desk' },
  { id: 'mouse', name: 'Glow Mouse', price: 459, image: '/images/glow 2.jpeg', description: 'A compact wireless mouse with a little more personality.', category: 'Accessories' },
];
const money = (value) => `₹${value.toLocaleString('en-IN')}`;

export default function NavAirLanding() {
  const [variant, setVariant] = useState(0); const [slide, setSlide] = useState(0); const [mobileOpen, setMobileOpen] = useState(false); const [cartOpen, setCartOpen] = useState(false); const [checkoutOpen, setCheckoutOpen] = useState(false); const [cart, setCart] = useState([]); const [faq, setFaq] = useState(0);
  const promos = [{ title: 'Bloom Tumbler', line: 'A brighter way to hydrate', image: variants[variant][1], price: 749, tone: 'mint' }, { title: 'Cloud Headphones', line: 'Soft sound for loud days', image: products[1].image, price: 799, tone: 'sky' }, { title: 'Keyboard + Mouse', line: 'Refresh your desk setup', image: products[2].image, price: 849, tone: 'peach' }, { title: 'Glow Mouse', line: 'Small move, big mood', image: products[3].image, price: 459, tone: 'lilac' }];
  useEffect(() => { const timer = setInterval(() => setSlide((value) => (value + 1) % promos.length), 5000); return () => clearInterval(timer); }, [promos.length]);
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]); const shipping = cart.length ? 99 : 0; const total = subtotal + shipping; const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  const add = (product, selectedVariant) => { setCart((items) => { const key = `${product.id}-${selectedVariant || ''}`; const existing = items.find((item) => `${item.id}-${item.variant || ''}` === key); return existing ? items.map((item) => item === existing ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1, variant: selectedVariant }]; }); setCartOpen(true); toast.success(`${product.name} added to your bag`); };
  const change = (item, amount) => setCart((items) => items.flatMap((current) => current === item ? (current.quantity + amount > 0 ? [{ ...current, quantity: current.quantity + amount }] : []) : [current]));
  const jump = (id) => { setMobileOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  return <main className="nav-air-page" id="top">
    <div className="announcement"><Sparkle size={14} /> Bloom Tumbler · 1200 ml · ₹749 <button onClick={() => jump('shop')}>Shop now <ArrowRight size={14} /></button></div>
    <header className="site-header"><button className="brand" onClick={() => jump('top')}><span className="brand-mark">N</span><span>NAV AIR</span></button><nav className={mobileOpen ? 'desktop-nav open' : 'desktop-nav'}><button onClick={() => jump('shop')}>Shop</button><button onClick={() => jump('categories')}>Categories</button><button onClick={() => jump('bloom')}>Tumblers</button><button onClick={() => jump('cloud')}>Audio</button><button onClick={() => jump('about')}>About</button></nav><div className="header-actions"><button aria-label="Search"><Search size={19} /></button><button className="bag-button" onClick={() => setCartOpen(true)} aria-label={`Shopping bag, ${count} items`}><ShoppingBag size={20} />{count > 0 && <span>{count}</span>}</button><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen ? <X size={22} /> : <Menu size={22} />}</button></div></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">Everyday objects, elevated</p><h1>Make everyday<br /><em>feel lighter.</em></h1><p className="hero-description">Thoughtfully selected essentials for your desk, commute, and daily rituals.</p><div className="hero-buttons"><button className="button button-primary" onClick={() => jump('shop')}>Shop the collection <ArrowRight size={16} /></button><button className="text-link" onClick={() => jump('about')}>Why NAV AIR</button></div></div><div className="hero-art"><div className="art-sun" /><span className="hero-label">NEW<br /><b>DROP</b></span><img className="hero-product float" src={variants[variant][1]} alt={`${variants[variant][0]} Bloom Tumbler`} /><div className="hero-note"><span>{variant + 1} / 04</span><strong>{variants[variant][0]}</strong><small>Bloom Tumbler · {money(749)}</small></div><div className="variant-dots">{variants.map(([name], index) => <button key={name} className={variant === index ? 'selected' : ''} onClick={() => setVariant(index)} aria-label={`Select ${name}`}><i className={`dot dot-${index}`} /></button>)}</div></div></section>
    <section className="promo-carousel section" aria-label="Promotions"><div className={`promo-card ${promos[slide].tone}`}><div><p className="eyebrow">NAV AIR edit · 0{slide + 1}</p><h2>{promos[slide].title}</h2><p>{promos[slide].line}</p><strong>{money(promos[slide].price)}</strong><button className="button button-primary" onClick={() => jump('shop')}>Shop now <ArrowRight size={16} /></button></div><img src={promos[slide].image} alt={promos[slide].title} /></div><div className="promo-dots">{promos.map((promo, index) => <button key={promo.title} className={slide === index ? 'active' : ''} onClick={() => setSlide(index)} aria-label={`Show ${promo.title}`} />)}</div></section>
    <section className="section" id="shop"><div className="section-heading"><div><p className="eyebrow">The collection</p><h2>Good things,<br /><em>ready to go.</em></h2></div><p>Compact, useful, and designed to bring a little lift to the everyday.</p></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><div className="product-visual"><span>{product.category}</span><img src={product.image} alt={product.name} /><button onClick={() => add(product, product.id === 'bloom' ? variants[variant][0] : undefined)} aria-label={`Add ${product.name} to cart`}><Plus size={18} /></button></div><div className="product-info"><div><h3>NAV AIR {product.name}</h3><p>{product.description}</p></div><strong>{money(product.price)}</strong></div><button className="card-link" onClick={() => add(product, product.id === 'bloom' ? variants[variant][0] : undefined)}>Add to cart <ArrowRight size={15} /></button></article>)}</div></section>
    <section className="bloom-editorial section" id="bloom"><div className="editorial-copy"><p className="eyebrow">01 · Drinkware</p><h2>Hydration,<br /><em>with personality.</em></h2><p>Bloom is a 1200 ml stainless steel tumbler made for hot and cold drinks, busy commutes, slow mornings, and everything between.</p><button className="button button-light" onClick={() => add(products[0], variants[variant][0])}>Shop Bloom <ArrowRight size={15} /></button></div><img className="editorial-image" src={variants[variant][1]} alt="NAV AIR Bloom floral tumbler" /><div className="feature-list"><span><b>1200</b>ML CAPACITY</span><span><b>HOT + COLD</b>READY</span><span><b>4</b>FLORAL COLORS</span></div></section>
    <section className="section variant-section"><div className="section-heading centered"><div><p className="eyebrow">Find your flower</p><h2>Pick your<br /><em>colour story.</em></h2></div><p>Blue, white, purple, or pink. Your everyday, your way.</p></div><div className="variant-grid">{variants.map(([name, image], index) => <button className={`variant-card ${variant === index ? 'active' : ''}`} key={name} onClick={() => setVariant(index)}><img src={image} alt={name} /><strong>{name}</strong><small>{money(749)}</small></button>)}</div></section>
    <section className="cloud-section section" id="cloud"><div className="cloud-image"><img src={products[1].image} alt="NAV AIR Cloud Headphones" /></div><div className="cloud-copy"><p className="eyebrow">02 · Audio</p><h2>Your own<br /><em>little cloud.</em></h2><p>Wireless Bluetooth sound, deep bass, soft ear cushions, and a lightweight foldable build for wherever the day takes you.</p><div className="chips"><span>Wireless</span><span>Deep bass</span><span>Foldable</span></div><button className="button button-primary" onClick={() => add(products[1])}>Add to cart · {money(799)}</button></div></section>
    <section className="section categories" id="categories"><div className="section-heading centered"><div><p className="eyebrow">Shop by category</p><h2>Find your<br /><em>next favourite.</em></h2></div></div><div className="category-grid">{['Drinkware', 'Audio', 'Gaming / Desk', 'Accessories'].map((category) => <button key={category} onClick={() => jump('shop')}><span>{category}</span><small>Explore the edit</small><ArrowRight size={18} /></button>)}</div></section>
    <section className="story-section section" id="about"><div className="story-mark">na<span>✦</span></div><div><p className="eyebrow">Why NAV AIR</p><h2>Useful can be<br /><em>beautiful too.</em></h2><p>We look for modern, practical products that earn their place in your day. No noise, no clutter — just things that feel good to use.</p></div><ul><li>Thoughtfully selected products</li><li>Modern everyday design</li><li>Shopping made simple</li></ul></section>
    <section className="faq-section section"><div><p className="eyebrow">Good to know</p><h2>Questions,<br /><em>answered.</em></h2></div><div>{['How much is shipping?', 'What is Bloom made for?', 'Can I choose a different Bloom colour?'].map((question, index) => <div className="faq-item" key={question}><button onClick={() => setFaq(faq === index ? null : index)}><span>{question}</span><ChevronDown size={18} /></button>{faq === index && <p>{index === 0 ? 'Standard shipping is ₹99 per order across India.' : index === 1 ? 'Bloom is made for hot and cold drinks and holds 1200 ml.' : 'Yes. Select your preferred colour before adding Bloom to your cart.'}</p>}</div>)}</div></section>
    <footer className="site-footer"><div className="footer-top"><button className="brand" onClick={() => jump('top')}><span className="brand-mark">N</span><span>NAV AIR</span></button><p>Everyday essentials,<br /><em>with a little lift.</em></p><button className="button button-primary" onClick={() => jump('shop')}>Shop everything <ArrowRight size={15} /></button></div><div className="footer-bottom"><span>© 2026 NAV AIR</span><span>Support · Policies · Contact</span><span>Made for the everyday</span></div></footer>
    {cartOpen && <div className="drawer-backdrop" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-header"><div><p className="eyebrow">Your cart</p><h2>{count ? `${count} ${count === 1 ? 'item' : 'items'}` : 'Your cart is empty'}</h2></div><button onClick={() => setCartOpen(false)} aria-label="Close cart"><X size={20} /></button></div>{cart.length ? <><div className="drawer-items">{cart.map((item) => <div className="drawer-item" key={`${item.id}-${item.variant}`}><img src={item.image} alt="" /><div><strong>{item.name}</strong>{item.variant && <small>{item.variant}</small>}<span>{money(item.price)}</span><div className="quantity"><button onClick={() => change(item, -1)} aria-label="Decrease quantity"><Minus size={13} /></button><b>{item.quantity}</b><button onClick={() => change(item, 1)} aria-label="Increase quantity"><Plus size={13} /></button></div></div></div>)}</div><div className="drawer-summary"><p><span>Subtotal</span><strong>{money(subtotal)}</strong></p><p><span>Shipping</span><strong>{money(shipping)}</strong></p><p className="total"><span>Total</span><strong>{money(total)}</strong></p><button className="button button-primary full" onClick={() => { setCartOpen(false); setCheckoutOpen(true); }}>Checkout <ArrowRight size={15} /></button></div></> : <div className="empty-cart"><ShoppingBag size={30} /><p>Good things are waiting.</p><button className="button button-primary" onClick={() => setCartOpen(false)}>Keep shopping</button></div>}</aside></div>}
    {checkoutOpen && <Checkout cart={cart} subtotal={subtotal} shipping={shipping} total={total} close={() => setCheckoutOpen(false)} />}
  </main>;
}
function Checkout({ cart, subtotal, shipping, total, close }) { const [form, setForm] = useState({ fullName:'', email:'', phone:'', address:'', landmark:'', city:'', state:'', pincode:'' }); const [status, setStatus] = useState(''); const update = (key, value) => setForm({ ...form, [key]: value }); const submit = async (event) => { event.preventDefault(); setStatus('Submitting…'); try { const response = await fetch(`${process.env.REACT_APP_BACKEND_URL || 'http://localhost:5000'}/api/orders/create`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ ...form, mobile:form.phone, product:cart.map((item) => `${item.name}${item.variant ? ` (${item.variant})` : ''} x${item.quantity}`).join(', '), color:cart.find((item) => item.variant)?.variant || '', price:total }) }); if (!response.ok) throw new Error(); setStatus('Order received. We will be in touch shortly.'); } catch { setStatus('We could not submit the order right now. Please try again.'); } }; return <div className="checkout-backdrop"><div className="checkout-modal"><button className="close-checkout" onClick={close} aria-label="Close checkout"><X size={20} /></button><div className="checkout-summary"><p className="eyebrow">NAV AIR checkout</p><h2>Almost<br /><em>yours.</em></h2>{cart.map((item) => <div className="checkout-item" key={`${item.id}-${item.variant}`}><img src={item.image} alt="" /><span>{item.name}<small>Qty {item.quantity}{item.variant ? ` · ${item.variant}` : ''}</small></span><strong>{money(item.price * item.quantity)}</strong></div>)}<p><span>Subtotal</span><strong>{money(subtotal)}</strong></p><p><span>Shipping</span><strong>{money(shipping)}</strong></p><p className="grand"><span>Total</span><strong>{money(total)}</strong></p></div><form onSubmit={submit}><p className="eyebrow">Delivery details</p><div className="form-grid">{[['fullName','Full name'],['email','Email'],['phone','Phone'],['address','Address'],['landmark','Landmark (optional)'],['city','City'],['state','State'],['pincode','PIN code']].map(([key,label]) => <label key={key} className={key === 'address' || key === 'landmark' ? 'wide' : ''}>{label}<input required={key !== 'landmark'} value={form[key]} onChange={(event) => update(key,event.target.value)} /></label>)}</div><button className="button button-primary full" type="submit">Place order <ArrowRight size={15} /></button>{status && <p className="form-status">{status}</p>}<small className="secure-note">Standard shipping · ₹99 · No payment is collected here.</small></form></div></div>; }
